### ISSUE TITLE
Param /p:config=Release with /p:platform=Win32 not working

### ISSUE THREAD

**Issue by diegoperes** [magicxor/radstudio-docker#1]
Hello, only works with the parameter "Debug" in Release the error occurs: Unit 'Vcl.Forms' not found.

How do I copy the executable to my host?

Thank you! Excellent initiative.

**Comment by magicxor** [comment]
> Hello, only works with the parameter "Debug" in Release the error occurs: Unit 'Vcl.Forms' not found.

Hello. I think that you're speaking about `10.1-delphi-net3.5-ltsc2019`. It's an experimental image: silent installation isn't working for RAD Studio >= XE6 so I'm trying to create some setup script by myself. At this point, it seems that some files are missing from `C:\Program Files (x86)\Embarcadero\Studio\18.0\lib\win32\release`:

![image](https://user-images.githubusercontent.com/8275793/82760533-a573d880-9e26-11ea-8b7b-81f58d3d848c.png)

I'll try to fix that, but not sure how much time it takes. For now you could use `xe-delphi-net3.5-ltsc2019` if it meets your needs.

> How do I copy the executable to my host?

You can use [docker cp](https://docs.docker.com/engine/reference/commandline/cp/):

`docker cp <your_container_id>:"C:\build\your_project" "C:\apps\your_project"`

or just use `-v` argument

`docker run -v C:\host_dir:C:\build\app magicxor/radstudio:xe-delphi-net3.5-ltsc2019 msbuild /t:build C:\build\app\Project1.dproj`

**Comment by magicxor** [comment]
> silent installation isn't working for RAD Studio >= XE6

I was wrong: it works up to [xe8 upd1](https://github.com/magicxor/radstudio-docker/tree/master/xe8upd1-delphi-net3.5-ltsc2019).

**Comment by magicxor** [comment]
@diegoperes check out 10.3.3-delphi-net4.8-ltsc2019
(Fixed with new [hook project](https://github.com/magicxor/ExtractArchiveHook))
