### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by diegoperes** [magicxor/radstudio-docker#2]
Hi,
How can I solve the problem of accented characters? Here we use for example in our Hello World in Portuguese "Olá Mundo" after compiled displays "?" in place of "á".
I changed the LANGDIR variable to empty but it didn't work.
[System.Environment]::SetEnvironmentVariable('LANGDIR', '', [System.EnvironmentVariableTarget]::Machine);
    
![image](https://user-images.githubusercontent.com/5603723/83172153-8bb7e700-a0ed-11ea-997d-ebb68066a76b.png)

10.3.3-delphi-net4.8-ltsc2019

**Comment by magicxor** [comment]
How that's related to this repository? I guess the problem is in your project, isn't it?

![image](https://user-images.githubusercontent.com/8275793/83205423-17c71e80-a181-11ea-8980-88c043617982.png)

**Comment by diegoperes** [comment]
Tested here, in Win64 is working correctly. This problem is happening only in Win32.

**Comment by magicxor** [comment]
![image](https://user-images.githubusercontent.com/8275793/83217575-ab5b1800-a19e-11ea-9a5f-642330e6119b.png)

Unfortunately, I still can't reproduce the problem. Please provide a repro.

**Comment by diegoperes** [comment]
You are right, to resolve it I set it to "1252" in Project Options> Building> Delphi Compiler> Compiling> Code Page

Thank's for your time.
