### ISSUE TITLE
RAD Studio 10.2 Rio

### ISSUE THREAD

**Issue by delphihobbit** [magicxor/radstudio-docker#3]
Thank you very much for these images, they're great!

I'd like to build a image for RAD Studio 10.2 Rio.
Looking at what you did for the more recent versions, it looks like you had to reverse engineer the installer, specifically the passwords for the respective 7zip files and their installation locations. I assume this is due the fact that the silent installer is broken.

Could you elaborate on how you did that?
I'd be happy to follow your process to create a 10.2 image.

**Comment by magicxor** [comment]
Hi @delphihobbit, I'm glad to hear that you like my work.

> Looking at what you did for the more recent versions, it looks like you had to reverse engineer the installer, specifically the passwords for the respective 7zip files and their installation locations. I assume this is due the fact that the silent installer is broken.

Yep, you're right.

1) Please take a look at https://github.com/magicxor/ExtractArchiveHook - this could help you to intercept 7zip passwords. (You can use a debugger instead: ollydbg, x64dbg, etc. Your target is ExtractArchive function in mia.lib binary).

2) Unpack these 7zips

3) Install the full version of RAD Studio IDE (activated, not the trial one)

4) Use some tool like [RadStudioFileTracker](https://gist.github.com/magicxor/eb8c31a2d083389f92591960c3c7c1ff) to get correspondence between installed IDE files and 7zips
