### ISSUE TITLE
way to remove .NET for a smaller image ?

### ISSUE THREAD

**Issue by goulu** [magicxor/radstudio-docker#4]
First, thanks a lot for your work which saved us a lot of time!
We're using xe5upd2-delphi-net3.5-ltsc2019 to compile win32 non managed code only, on Azure DevOps.
The image is 2.6 Gigs and takes ~15 minutes to install in the pipeline.
Is there a way to make it smaller ? I tried not to use .NET by using `FROM mcr.microsoft.com/windows/servercore:ltsc2019`
but the Delphi installer hangs without notice...
Is there a way to remove .NET after the install ? or can you think of another way of making the image much smaller ?
Thanks !

**Comment by magicxor** [comment]
Hi @goulu. I don't think there is a way to significantly reduce image size. But you could try `10.4-delphi-net4.8-ltsc2019` or `xe8upd1-delphi-net3.5-ltsc2019` which are smaller.

**Comment by magicxor** [comment]
I have uploaded ltsc2022 images that are smaller than ltsc2019.
